// <auto-generated />
namespace SoftwareIIb.Migrations
{
    using System.CodeDom.Compiler;
    using Microsoft.EntityFrameworkCore.Migrations;

    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initialize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialize));
        
        string IMigrationMetadata.Id
        {
            get { return "202404202006433_initialize"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
