using System.CodeDom.Compiler;
using Microsoft.EntityFrameworkCore.Migrations;

using System.Resources;
// <auto-generated />
namespace SoftwareIIb.Migrations
{
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class nullableForeignKeys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nullableForeignKeys));
        
        string IMigrationMetadata.Id
        {
            get { return "202404202210465_nullableForeignKeys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
